spring:
  workload: ${workload:genericWorkload}
  jpa:
    open-in-view: false
  flyway:
    enabled: false
  datasource:
    hikari:
      username: ${dbuser:yugabyte}
      password: ${dbpassword:yugabyte}
      connection-init-sql: 'set yb_read_from_followers to true;'
      maximumPoolSize: ${max-pool-size:10}
      maxLifeTime: ${max-life-time:3600000}
      data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
      data-source-properties:
#        preferQueryMode: org.postgresql.jdbc.PreferQueryMode.EXTENDED_CACHE_EVERYTHING
        serverName: ${node:127.0.0.1}
        portNumber: ${port:5433}
        databaseName: ${dbname:yugabyte}
        #ssl: ${ssl:false}
        #sslmode: ${sslmode:disable}
        #sslrootcert: ${sslrootcert:~/.ssh/ybcloudcert/root.crt}
  data:
    cassandra:
      local-datacenter: ${datacenter_c:DC1}
      port: ${port_c:9042}
      contact-points: ${node_c:127.0.0.1}
      userid: ${userid_c:cassandra}
      password: ${password_c:yugabyte}

logging.level:
  root: ERROR
  java.sql: DEBUG
  com.zaxxer.hikari: TRACE
  com.yugabyte: DEBUG
  com.yugabyte.simulation.workload: DEBUG
  org.springframework.jdbc.core: ERROR 
    
server:
  port: 8080
  