spring:
  jpa:
    open-in-view: false
  flyway:
    enabled: false
  datasource:
    hikari:
#      username: ${user:yugabyte}
      username: yugabyte
      password: ${password:yugabyte}
      maximumPoolSize: ${max-pool-size:100}
      maxLifeTime: ${max-life-time:3600000}
      data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
      data-source-properties:
        serverName: ${node:127.0.0.1}
        portNumber: ${port:5433}
        databaseName: ${dbname:yugabyte}
        #ssl: ${ssl:false}
        #sslmode: ${sslmode:disable}
        #sslrootcert: ${sslrootcert:~/.ssh/ybcloudcert/root.crt}

logging.level:
  java.sql: DEBUG
  com.zaxxer.hikari: TRACE
  com.yugabyte: ERROR
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  com.yugabyte.simulation.workload: DEBUG