# use this profile for running the app on xcluster. Put in new IPs, when they are ready.
spring:
  jpa:
    open-in-view: false
  flyway:
    enabled: false
  datasource:
    hikari:
      username: yugabyte
      password: yugabyte
      maximumPoolSize: 100
      maxLifeTime: 3600000
      data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
      data-source-properties:
        serverName: 172.161.29.86
        portNumber: 5433
        databaseName: yugabyte
        additionalEndpoints: 172.161.29.136:5433,172.161.36.113:5433,172.161.44.66:5433,172.161.51.169:5433,172.161.61.54:5433
        topologyKeys: "aws.us-east-2.us-east-2a,aws.us-east-2.us-east-2b,aws.us-east-2.us-east-2c"


logging.level:
  java.sql: DEBUG
  com.zaxxer.hikari: TRACE
  com.yugabyte: ERROR
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE